apiVersion: v1
kind: Service
metadata:
  name: {{ include "venice.fullname" . }}-router
  labels:
    {{- include "venice.labels.router" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "venice.selectorLabels.router" . | nindent 4 }}
